### PR TITLE
Add GH Actions and format

### PR DESCRIPTION
**Pull request by KTibow**
This adds some GitHub Actions and formats with isort and black.

### CODE REVIEW

**Comment by gcobb321** [comment]
Thanks for reformatting with black but I won’t be merging this into the code under development and am closing this request. Although black is the standard used by the HA developers, I find it hard to read without variable declarations and other code lined up on the equal sign. I also find the reformatting of other conditional statements distracting in the python and javascript modules. Because of this, I think maintaining and updating the code would be more difficult and it is hard enough already. Since I I’m the developer and only one working on the code, I want to make it as easy as I can.

**Comment by KTibow** [comment]
Got it. Consider adding `validate.yaml` anyway?

**Comment by gcobb321** [comment]
Not sure what validate.yaml is but I'll look into it.

**Comment by KTibow** [comment]
Just the `.github/actions/validate.yaml`. Copy that file into your repo, and it'll automatically check HACS and hassfest on push.

**Pull request closed without merging**
