### PR TITLE
Fix issues when installing/upgrading with HACS

### PR DESCRIPTION
**Pull request by ludeeus**

### CODE REVIEW

**Comment by gcobb321** [comment]
I merge the PR. I thought that was the way I had everything before the first time it was hosed. Did you use those settings successfully? I think something else was going on since I couldn't even load my development 'icloud_dev' platform.

**Comment by ludeeus** [comment]
I do not use this integration, but I have a good amount of knowledge about [HACS](https://github.com/hacs/integration/graphs/contributors) ;)

**Comment by gcobb321** [comment]
I saw in the main blog that to rename the device_tracker folder to icloud3 and it should start working again. I hadn't tried that but I also have a custom_component/icloud3_dev folder with a device_tracker.py that I make updates to for testing. the device_tracker platform points to that folder. I've never had problems but when I tried to load that version, I got the same setup for device_tracker can not be found and it failed to load. It's almost like there is some other setting in HA somewhere that is getting hosed. Which makes no sense at all. Restarting HA, rebooting my Pi and a few other things had no effect. Renaming the device_tracker to something else and redoing the HACS install at one point hosed the home_assistant_v2.db log file so bad it wouldn't add any log entries from an HA component until I deleted it and rebooted the Pi again.

Any chance you could do a HACS update to see if you have any issues? I'll try again and rename the d_t directory to icloud3 and see what happens.

**Comment by ludeeus** [comment]
Untill this PR is in a release updates will still fail.
HACS downloads the files from the tag of the release, it also uses the `domain` key of the manifest to create the folder under `custom_components`

The reason it fails now, is that custom_components takes president over core components.
By having the folder named `device_tracker` HA will not load the core `device_tracker` domain, and every device tracker that depends on it (and it's functions) will fail.

**Comment by gcobb321** [comment]
Understand. 
I have just updated the v2.0.1 release so the Releases tag contains file=manifest.json with domain=icloud3, and the hacs.json in the icloud3 root directory has domains=device_tracker. I thought that is the way I had it. Maybe not. Will do a backup and then retry with HACS in a few minutes if that is correct.

Comments or advice...

**Comment by ludeeus** [comment]
<https://github.com/gcobb321/icloud3/blob/v2.0.1/custom_components/icloud3/manifest.json#L2>
This is what HACS see.

My PR deleted the `custom_components/icloud3/hacs.json` file since that is not used at all.

**Comment by gcobb321** [comment]
I just did a reedit of the Releases to delete the old manifest.json and add another correct one (below) as you had it. The file, as it is right now is:
{
  "domain": "icloud3",
  "name": "iCloud3 Device Tracker",
  "documentation": "https://gcobb321.github.io/icloud3/#/",
  "dependencies": [],
  "codeowners": ["@gcobb321"],
  "requirements": []
}
which is the way it has been for a long time. I changed it earlier today to the one that is wrong trying to get HACS to update to the icloud3 directory rather than the device_tracker directory. Probably 2 problems fixed incorrectly which compounded errors. Am going to do a HACS update now and see what happens.

So the hacs.json goes in the Releases and not on the master branch. Will redelete it from there.

**Pull request merged**
